### ISSUE TITLE
MalihuScrollbarService / MalihuScrollbarDirective not exported in the bundle

### ISSUE THREAD

**Issue by philippejer** [jfcere/ngx-malihu-scrollbar#18]
Hello,

Looking at the npm bundle in the current version 1.2.1 (node_modules\ngx-malihu-scrollbar\dist\bundles\ngx-malihu-scrollbar.umd.js) it seems only MalihuScrollbarModule is exported, not the directive or service, so the service cannot be injected (MalihuScrollbarService is undefined and cannot be used as a token).

Reproduced here: https://plnkr.co/edit/YQaW13j5sW5n7xKjjX7F

(BTW thanks for the performance in 1.2.1, it seems to work fine, the dirty checking is not invoked on each auto-update anymore).

Regards,
Jeremy

**Comment by jfcere** [comment]
Hi @philippejer,

Thanks for the plunker, you have to import `MalihuScrollbarModule` in the `AppModule` for the service to be registered but even when It's done, you are right there is still a problem as `MalihuScrollbarService` does not seems to be exported in the bundle files.

I updated the plunker with the import statement for `MalihuScrollbarModule`:
https://plnkr.co/edit/udrbMTov42xcQ69fSIVl

I'm going to take a look at it this weekend ... I'll keep you in touch.

**Comment by jfcere** [comment]
Bundle exports are not fixed, please update to [v1.2.2](https://github.com/jfcere/ngx-malihu-scrollbar/releases/tag/v1.2.2).

I updated the plunker with latest version and it works fine now:
https://plnkr.co/edit/MU8D0sMfEXiLifAnCm5X

**Comment by philippejer** [comment]
Hi @jfcere,

Just upgraded to 1.2.2  and it works perfectly, thanks for the quick resolution!

Regards,
Jeremy
