### ISSUE TITLE
Hide default document scrollbar 

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [jfcere/ngx-malihu-scrollbar#21]
How can I add this to html body, which can hide default browser scrollbar and display custom scrollbar ?

**Comment by jfcere** [comment]
@rajjaiswalsaumya sorry about the delay, I'm gonna have to take a look as my first attempt didn't seems to work when applying malihu scrollbar on the body.

I'll come back to you shortly!

**Comment by jfcere** [comment]
@rajjaiswalsaumya better late than never!

You can now apply custom scrollbar on `body` element using `MalihuScrollbarService`.

Plese update to [v1.3.0](https://github.com/jfcere/ngx-malihu-scrollbar/releases/tag/v1.3.0) and refer to the [FAQ](https://github.com/jfcere/ngx-malihu-scrollbar#faq) section on README.md for details.
