### ISSUE TITLE
_this.scrollableElement.mCustomScrollbar is not a function

### ISSUE THREAD

**Issue by kathiraashi** [jfcere/ngx-malihu-scrollbar#22]
`import { MalihuScrollbarModule } from 'ngx-malihu-scrollbar';`

**Comment by nilasissen** [comment]
yup facing same issue

**Comment by jfcere** [comment]
Are you guys getting the error when using the UMD bundle file?

**Comment by jfcere** [comment]
[Plunker](https://plnkr.co/edit/PPSjqjkznk6I3H0qSIXL?p=preview) is functional after adding jQuery and Malihu Custom Scrollbar javascript files.

Have you guys included those in your application as well?

As the error seems to point in the direction that it could not find `mCustomScrollbar` jQuery extension method.

**Comment by nilasissen** [comment]
thanks for seeing it ! yes i have followed your guide and  jquery & malihu js is included in my project . Thanks for the plunker let me check it first

**Comment by unikzforce** [comment]
mine too,
anyway the plunkr is broken

**Comment by jfcere** [comment]
Sorry .. i updated the link in the comment.

**Comment by unikzforce** [comment]
thank you very much @jfcere ..
but my problem with the "mCustomScrollbar is not a function" is not resolved yet.
would you please guide me how to setup this lib with angular-cli and webpack .. i've just followed the instructions but still could not get it to work. could you please setup a working plunkr using webpack and angular-cli instead of SystemJs?

**Comment by jfcere** [comment]
Unfortunately plunker only works with SystemJS and does not work with Angular-CLI or webpack.

**Angular-CLI**
Follow the [installation](https://github.com/jfcere/ngx-malihu-scrollbar#installation) section of the `readme.md` and/or take a look at the repository as it includes a demo-app already setup with Angular-CLI.

**SystemJS**
For SystemJS you can refer to the plunker [example](https://plnkr.co/edit/JcSTXc?p=preview) that uses CDN for `jQuery` and `malihu-custom-scrollbar-plugin`.

**Webpack only**
I do not have an example yet for poeple using webpack only (without Angular-CLI). I'll try to work on that in a near future.

**Comment by jfcere** [comment]
I'd like to help more about the issue but my attempts have all succeeded on my side with both SystemJS and Angular-CLI.

Can any of you provide a repository that has the issue?

**Comment by nilasissen** [comment]
@jfcere i am not sure wat was the issue but after using ur plunkr it worked for me currently i am using it and its working fine. @unikzforce  did u import it as service ? u have to import 
 import { MalihuScrollbarModule,MalihuScrollbarService } from 'ngx-malihu-scrollbar';
both.

**Comment by jfcere** [comment]
@unikzforce any update following previous comment?

**Comment by einer20** [comment]
Restarting the ng serve worked for me.

**Comment by jfcere** [comment]
Closing as it seems to work for the majority of people, please reopen if there is anything.
