### ISSUE TITLE
remove jquery dependency in project

### ISSUE THREAD

**Issue by tamohugues** [jfcere/ngx-malihu-scrollbar#28]
Can you provide new version without dependency of jquery in the project ?

because Jquery is not good for angular >= 2
And use only the angular component for the ngx-malihu-scrollbar implementation.
We love your work, but we are reluctant to use the module because of the dependency with JQuery. Plz can you update if is possible and remove Jquery dépendency.

**Comment by jfcere** [comment]
@tamohugues I would if I could ...

I only wrapped an existing library that use JQuery: https://github.com/malihu/malihu-custom-scrollbar-plugin

The owner would have to rewrite the plugin with pure JS instead of JQuery. If he does I would follow his changes and removes the dependcy.
