### ISSUE TITLE
the name 'MalihuScrollbarService' was not found

### ISSUE THREAD

**Issue by shierone** [jfcere/ngx-malihu-scrollbar#31]
Hi, I've tried to import the script into my angular project and I want to use it in a component with the Service method. But after following the instructions the compiler gives me this error:

`error TS2304: Cannot find name 'MalihuScrollbarService'`

refering to the MalihuScrollbarService in the constructor (private mScrollbarService:  MalihuScrollbarService)

Still quite new to angular by the way.

**Comment by jfcere** [comment]
Hi @shierone, did you add `MarkdownModule.forRoot()` to the list of imports in your `AppModule` ?

**Comment by jfcere** [comment]
Close for inactivity, please reopen if there is anything.
