### ISSUE TITLE
Can't bind to 'scrollbarOptions' since it isn't a known property of 'div'.

### ISSUE THREAD

**Issue by muralimnmcse** [jfcere/ngx-malihu-scrollbar#32]
I get this error message in Angular 5 - Can't bind to 'scrollbarOptions' since it isn't a known property of 'div'.

Angular CLI: 1.6.8
Node: 8.9.1
OS: win32 x64
Angular: 5.0.1
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/animations: 5.2.1
@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0

**Comment by jfcere** [comment]
You added `MalihuScrollbarModule.forRoot()` to the list of imports in your `AppModule`?

#### app.module.ts
```diff
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
+ import { MalihuScrollbarModule } from 'ngx-malihu-scrollbar';

import { AppComponent } from './app.component';

@NgModule({
  imports: [
    CommonModule,
+   MalihuScrollbarModule.forRoot(),
  ],
  declarations: [AppComponent],
})
```
And used `scrollbarOptions` with `malihu-scrollbar` directive like this?

#### example.component.ts
```typescript
public scrollbarOptions = { axis: 'yx', theme: 'minimal-dark' };
```
#### example.component.html
```html
<div malihu-scrollbar [scrollbarOptions]="scrollbarOptions">
   Lorem ipsum dolor sit amet, consectetur adipisicing elit...
</div>
```

**Comment by muralimnmcse** [comment]
Yes did exactly the same.

**Comment by luchillo17** [comment]
Mine works but VSCode screams at me:
![image](https://user-images.githubusercontent.com/9698639/38277560-6e7ae552-375e-11e8-8fcd-2ba9c8333cfa.png)
