### ISSUE TITLE
Question: How did you implement this in your materialize sidnav?

### ISSUE THREAD

**Issue by theiviaxx** [jfcere/ngx-malihu-scrollbar#34]
I cant seem to get the scrollbar to work using your materialize lib.  Just wondering if there was a trick to it or something to look for?

Great projects, btw!!

**Comment by jfcere** [comment]
@theiviaxx thx!

I used the `MalihuScrollbarService` to initialize the scrollbar by targeting the sidenav.

You can see the code here: https://github.com/sherweb/ng2-materialize/blob/master/demo-app/src/app/app.component.ts#L47-L49
