### ISSUE TITLE
Require Update

### ISSUE THREAD

**Issue by lovep34** [jfcere/ngx-malihu-scrollbar#39]
Can you please update so it will work with Angular 5 and 6, Also please setup the different demos and github projects for component approach, Service approach etc. Now it is little bit confusing.

**Comment by jfcere** [comment]
Last time I checked the library was working for both Angular 5 and 6 (you can see the demo of [ngx-materialize](https://sherweb.github.io/ngx-materialize) that is using it for the sidenav and the project is in Angular 6).

Can you reproduce your problem in (https://stackblitz.com/)[https://stackblitz.com/] ?

For the service approach, I am a little confused as it is documented in the [README.md](https://github.com/jfcere/ngx-malihu-scrollbar#service).

Do you have any specific question?

**Comment by lovep34** [comment]
Hi @jfcere 

That's good! I think this is little bit confusing as you have merged all approach in single project, I suggest you to create different project for every approach so it will be easy to understand.

I want to use Component approach.

One more thing on your documentation the script location is not correct, i.e:
+ "../node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"

Thanks

**Comment by lovep34** [comment]
Hi @jfcere ,

I have installed both dependencies and embed the code in .ts and HTML file, everything is fine, now it is showing object in Firebug, can you please suggest

![image](https://user-images.githubusercontent.com/41196164/44344263-e26ea680-a4ad-11e8-8165-007ab75ea97b.png)

Also I have try to create Stackblitz but when I import jQuery dependency, it broke my project. you can see it here.
https://stackblitz.com/edit/angular-svyvky

**Comment by GMaxera** [comment]
I don't see how is it possible to use with Angular 6 if the latest release explicitly block installation:

ngx-malihu-scrollbar@1.3.2 requires a peer of @angular/core@^2.4.0 || ^4.0.0 || ^5.0.0

Any advice ?

**Comment by Carlosps** [comment]
Do you have any idea why I am getting a "ReferenceError: $ is not defined at MalihuScrollbarDirective.initElements (malihu-scrollbar.directive.js:22)" message?

I am using Angular 5

**Comment by jfcere** [comment]
Do you have included jQuery in your application and added both `jquery` and `mcustomscrollbar` types to `tsconfig.app.json` like written in the [README.md](https://github.com/jfcere/ngx-malihu-scrollbar#installation)?

#### .angular-cli.json

```diff
"styles": [
  "styles.scss",
+ "../node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css"
],
"scripts": [
+ "../node_modules/jquery/dist/jquery.min.js",
+ "../node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"
],
```

#### tsconfig.app.json

```diff
{
  "compilerOptions": {
    ...
    "types": [
+     "jquery",
+     "mcustomscrollbar"
    ]
  },
  ...
}

**Comment by jfcere** [comment]
Library has been updated to Angular 7, please update `ngx-malihu-scrollbar` to [v7.0.0](https://github.com/jfcere/ngx-malihu-scrollbar/releases/tag/v7.0.0).

**Comment by GMaxera** [comment]
Thank you. That's fine for me because I'm starting a new project and I can upgrade to Angular 7 my project too and it's fine.... but did you realized that in that way you will never released a version applicable to Angular 6 ? :-)

**Comment by jfcere** [comment]
@GMaxera This version is applicable to both Angular 6 and 7: 
https://github.com/jfcere/ngx-malihu-scrollbar/blob/master/lib/package.json#L27
