### ISSUE TITLE
Using Callbacks with Ng Custom functions

### ISSUE THREAD

**Issue by alexsalmon** [jfcere/ngx-malihu-scrollbar#4]
I'm trying to use the onTotalScroll callback to trigger a function in the component, which would "lazy load" more items into the scroll box:

```
ngOnInit() {
  this.scrollbarOptions = {
  axis: 'y',
  scrollButtons: {enable: false},
  scrollInertia: 250,
  theme: 'content-cloud',
  callbacks:{
    onTotalScroll: function() {
      console.log("End of Scroll");
      this.loadMore();
    }
  }
};

loadMore() {
  console.log("Loading more!");
};

```

However, the function loadMore() can't be found:

`EXCEPTION: this.loadMore is not a function`

I'm unsure about the best way to do this, because the function is trying to be called inside the callback inside the scrollbarOptions.

Any help is much appreciated!

**Comment by jfcere** [comment]
Hi @alexsalmon,

You will need to use an [Arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#No_binding_of_this) for the callback to be correctly aware of the context in which the `loadMore` function is declared.

So basically, changing `onTotalScroll: function() {...}` for `onTotalScroll: () => {...}` would do the trick.

```diff
ngOnInit() {
  this.scrollbarOptions = {
  axis: 'y',
  scrollButtons: {enable: false},
  scrollInertia: 250,
  theme: 'content-cloud',
  callbacks:{
-    onTotalScroll: function() {
+    onTotalScroll: () => {
      console.log("End of Scroll");
      this.loadMore();
    }
  }
};

loadMore() {
  console.log("Loading more!");
};
```
Happy to help :)

**Comment by alexsalmon** [comment]
**Works great!** Thank you for your quick reply!
