### ISSUE TITLE
Angular 8 support

### ISSUE THREAD

**Issue by GMaxera** [jfcere/ngx-malihu-scrollbar#46]
I'd like to update to Angular 8 my project but there is a dependencies conflict that would requires an update by this package:

Package "ngx-malihu-scrollbar" has an incompatible peer dependency to "zone.js" (requires "^0.8.26", would install "0.9.1").

**Comment by jfcere** [comment]
Hi @GMaxera,

Sure, I am going to update the package this weekend... i'll keep your posted!

**Comment by jfcere** [comment]
Library has been updated to Angular 8, please update ngx-malihu-scrollbar to [v8.0.0](https://github.com/jfcere/ngx-markdown/releases/tag/v8.0.0)

**Comment by GMaxera** [comment]
Thank you ! It worked

**Comment by aaron170** [comment]
Hello.

Can you please help me about this.?
I am also implementing in my Angular 8 project but nothing seems to work.
I have updated the plugin to v8.0.0. Still nothing happens.
Can you prepare a Demo for it. It would be helpful.

Thanks

**Comment by jfcere** [comment]
Hi @aaron170,

You can take a look at the [StackBlitz example](https://stackblitz.com/edit/ngx-malihu-scrollbar) or [clone the project](https://github.com/jfcere/ngx-malihu-scrollbar#demo-application) and look at the `demo` folder in the repository.

If you're still having problems to set up the plugin and you have a repository you want me to check for you I can do it.

**Comment by aaron170** [comment]
Hi Jean.

Thanks for the reply.

But still facing the issue. 
I have created a Demo for it. https://stackblitz.com/edit/angular-with-malihu-scrollbar

Please see where I am going wrong.
Also I am getting error in Terminal like

![error](https://user-images.githubusercontent.com/19680243/64261058-8906d780-cf49-11e9-8496-3a52a8c4136f.jpg)


Thanks for your help.
