### ISSUE TITLE
support for angular Version 9

### ISSUE THREAD

**Issue by ravik3592** [jfcere/ngx-malihu-scrollbar#54]
When we can expect angular 9 compatible version

**Comment by jfcere** [comment]
Hi @ravik3592,

Sure I'll do it this weekend.

**Comment by jfcere** [comment]
Update to Angular 9 has been done!
You can update ngx-markdown to [v9.0.0](https://github.com/jfcere/ngx-malihu-scrollbar/releases/tag/v9.0.0).
