### ISSUE TITLE
update to angular4, aot build get error

### ISSUE THREAD

**Issue by MinionsDave** [jfcere/ngx-malihu-scrollbar#7]
> ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function
or lambda with a reference to an exported function, resolving symbol Injectable in /Users/Dave/work/weishu-admin/node_modules/ngx-malihu-scrollbar/node_modules/@an
gular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Users/Dave/work/weishu-admin/node_modules/ngx-malihu-scrollbar/node_modules/@angular/core/src/di/
opaque_token.d.ts, resolving symbol OpaqueToken in /Users/Dave/work/weishu-admin/node_modules/ngx-malihu-scrollbar/node_modules/@angular/core/src/di/opaque_token.d
.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/Dave/work/weishu-admin/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

when I recently update to angular4 and angular cli 1.0.0, I try to aot build then I get this error, this is my package.json
`{
  "name": "isaqa",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.json",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.0.0",
    "@angular/router": "^4.0.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.1.1",
    "ng2-bootstrap": "^1.3.3",
    "ng2-ckeditor": "^1.1.6",
    "ngx-malihu-scrollbar": "^1.1.0",
    "ngx-mydatepicker": "^0.1.0",
    "ngx-tooltip": "^0.0.9",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "^2.0.40",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0-beta.4",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "^2.2.1"
  }
}
`

**Comment by jfcere** [comment]
Hi @MinionsDave,

I haven't updated to Angular 4 yet, I'll update and come back to you shortly.

Thanks,

**Comment by jfcere** [comment]
@MinionsDave this should be fixed with PR #6.

Please update to v1.1.1 and confirm if it works on your end.

**Comment by MinionsDave** [comment]
update to v1.1.1 fix the problem， thank you!
