### ISSUE TITLE
change Color

### ISSUE THREAD

**Issue by deephakdd** [jfcere/ngx-malihu-scrollbar#8]
Can we change color of the scroll bar . i would like to have the color of material themes .

is this possible ?
if so Please suggest on how that can be achieved

**Comment by jfcere** [comment]
Hi @deephakdd,

All the CSS can be overriden or you can even make your own custom CSS to completely modify the apparence of the scrollbar.

Use the original documentation of Malihu Scrollbar available here: [Scrollbar styling & themes](http://manos.malihu.gr/jquery-custom-content-scroller/#styling-section)

Let me know if you have any further question.

**Comment by jfcere** [comment]
@deephakdd as a follow up, have you been able to customize the scrollbar?

**Comment by jfcere** [comment]
I am closing the issue but feel free to reopen if you still need assistance on customizing the scrollbar.

**Comment by deephakdd** [comment]
hi , 
Thanks for the reply . i was able to override by changing in the jquery.mCustomScrollbar.css
i just have a small doubt ,

can i not simply override your classes in my css file?
i dont want to use jqery so i cant create a custom theme

thanks once again for the reply

**Comment by jfcere** [comment]
@deephakdd yes you can override the CSS it should work out of the box.
